### ISSUE TITLE
Autocomplete does not always work

### ISSUE THREAD

**Issue by rover-random** [mathworks/MATLAB-extension-for-vscode#148]
**Describe the bug**
Code completion for built-in MATLAB works:
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/114679215/9d91c41e-e1ef-49a5-bbc6-30fe671e4f68)

Say in my working directory `foobar` I have a namespace `mypackage`:
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/114679215/055ccb55-285f-4fa2-86f6-8822469a2d91)

I would like to be able to type in vscode `mypa` and see `mypackage` autocompleted, and from there the functions in the namespace `mypackage`. But I do not:
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/114679215/aced953a-4243-4985-b911-2549670fe99f)

Sometimes this happens for me, and sometimes it doesn't! I cannot discern why it sometimes works and sometimes does not. Things I have considered and have seemed to make some difference, but have not conclusively solved the problem:
 - Does my working directory need to contain `+mypackage`, or does a directory containing `+mypackage` only need to be on path? 
 - Do I need to have MATLAB open at the same time?

I am on Windows.

**Comment by dklilley** [comment]
Hi @rover-random , thanks for reaching out!

I believe the issue is that `+mypackage` needs to be on the path. By default, the current working directory in VS Code is not MATLAB's cwd, nor is it added to the path. We have received similar requests before (e.g. #98), so this is something which is on our radar.

In the file "Explorer" tab in VS Code, try right-clicking in some empty space (in your screenshot, anywhere below "myscript.m") and selecting "MATLAB: Add Folder To Path". Does autocompletion of `mypackage` and its subfunctions work after this?

**Comment by dklilley** [comment]
Glad to hear it!

We definitely want to improve this to be more seamless.
