### ISSUE TITLE
Request to Add Linter Encoding Setting in MATLAB Extension

### ISSUE THREAD

**Issue by xiayang-cmd** [mathworks/MATLAB-extension-for-vscode#29]
I'm currently using the MATLAB extension for VSCode, and I've run into an issue that I believe could be improved. The extension currently does not allow for setting the Linter Encoding, which is causing some difficulties in my workflow. 
 
there are several features from the MATLAB Unofficial extension that I miss in this one, including the ability to set the Linter Encoding. 
 
Could you please consider adding a feature to set the Linter Encoding in the MATLAB extension settings? I believe this would greatly improve the user experience for myself and others who are also using this extension.

This is the setting in MATLAB Unofficial
![image](https://github.com/mathworks/MATLAB-extension-for-vscode/assets/62921464/43645422-b7d9-4808-a427-8e2477d98c89)

**Comment by dklilley** [comment]
Thanks for reporting this!

I'm having some trouble reproducing an issue on my computer. Can you share some more information about what the problem is and how it impacts you?

Also, can you share some reproduction steps, so that I may try to reproduce this myself (for example, do I need to create a .m file with a specific encoding)?

**Comment by dklilley** [comment]
Closing due to no response.
